# Generated by Django 3.1.5 on 2021-02-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_savepostuser'),
        ('usercostumer', '0004_auto_20210224_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('type_notif', models.PositiveIntegerField(choices=[(1, 'like'), (2, 'follow'), (3, 'comment'), (4, 'mention')])),
                ('more_text', models.TextField(blank=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penerima', related_query_name='penerima', to='usercostumer.userprofil')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengirim', related_query_name='pengirim', to='usercostumer.userprofil')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
