# Generated by Django 3.1.5 on 2021-03-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_savepostuser'),
        ('notif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postingan', to='posts.post'),
        ),
    ]
