# Generated by Django 3.1.5 on 2021-02-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercostumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/image/post', width_field='width_field')),
                ('caption', models.TextField(blank=True, null=True)),
                ('width_field', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('height_field', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='usercostumer.userprofil')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='usercostumer.userprofil')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
