# Generated by Django 3.1.5 on 2021-01-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(height_field='height_field', upload_to='build/static/media/image/post', width_field='width_field'),
        ),
    ]
