# Generated by Django 3.1.5 on 2021-02-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercostumer', '0002_auto_20210224_1824'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='usercostumer.userprofil')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
