# Generated by Django 3.1.5 on 2021-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210129_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(height_field='height_field', upload_to='image/post', width_field='width_field'),
        ),
    ]
