# Generated by Django 3.1.5 on 2021-01-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210131_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/image/post', width_field='width_field'),
        ),
    ]
