# Generated by Django 3.1.5 on 2021-02-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210203_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like',
        ),
    ]
