# Generated by Django 3.1.5 on 2021-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210203_1808'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_likes',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_likes'),
        ),
    ]
