# Generated by Django 3.1.5 on 2021-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercostumer', '0002_auto_20210224_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='name',
            field=models.CharField(default=models.CharField(max_length=30), max_length=30),
        ),
    ]
