# Generated by Django 3.1.5 on 2021-02-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercostumer', '0004_auto_20210203_1821'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_followers',
        ),
    ]
