# Generated by Django 3.1.5 on 2021-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercostumer', '0005_auto_20210203_1807'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_followers',
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('user', 'following_user'), name='unique_followers'),
        ),
    ]
